syncthing-gui-passwd: ENC[AES256_GCM,data:Q+bbosQCwNLb2GG3HqpPdSqNHKt3FAbLaR0AaOo=,iv:nL8/QndfwV/RPlChZum22eKFsAvZg0xEJ/Limhae5uQ=,tag:1wEJ7A3n5fGePA7IMHwRNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19676vq2d77cp6xekzrjp04zk24ymdnp32t42sqznuxkk8xe3w9fsqsphrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUC9VdGVieExidWtPQkFv
            Q3dTcXRIZGtuQ3hCSlZKTjNwZFhsSFRCMW1jCmx4Q0dMRjRic25TNUJsekFvQ2FQ
            TU9JNTdIRmpMS0hYYTlVVFZPejVzbjAKLS0tIHNkVlJjdHRVQ1NHak1nR0dEd21D
            QU5VOEhlRlpKdGNUUG03TEZaS21CUjAKfw/M+MvUoWbcjMbX0M5+yEqmbYOxlbzp
            KIxR4fooeiM97KgA+u6gbSe2p2O9ZITZiWFY1iKrMYQIURAGPxMEjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T20:29:09Z"
    mac: ENC[AES256_GCM,data:LXEhLWwvRLcu9I5/PYL4Xw59VyeGWQSTQd13fGj1AdhNzepEamTZMC6iXSriP7MAQzdH793ts9SeCYrSgLxKJ/3953MEMbcUU5iO4Ii4cMY5e22NA6x1T4YIneidqam6bQei7LEmKJiy2fG+/Mx0IYP3kAnjdAx9bxY5iys1j7Y=,iv:QKch3PaV/ynlj23twerN1fB/x9V+aquubu07XEW+i2Q=,tag:I4wFSZx/+1xItryFkVy5Dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
