adguard-home-passwd-file: ENC[AES256_GCM,data:de814EPi2msXBZnxZtj2skt9QkGfp1U3XE9fEFlQ1gxGLmTmmx8/92QUq4iiBurT5hm+8sBVPLiKigQX6xwmbcm5,iv:AdZWsx835+/ZKyMA1NTpTvbaxXZOmv6BhHy/sjQHHe8=,tag:bd1E02Un0MF8xX+Q3LF7zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19676vq2d77cp6xekzrjp04zk24ymdnp32t42sqznuxkk8xe3w9fsqsphrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWmthUlVNY29tbWNKTjdJ
            a2JCSURqOGZselZxU3gyNWdqS0w2ajJhRmxnCjBXL1EyUWVEUEpJK2dUSmZkTjBV
            THJCT0gxTFZHTnc0UUV1WjhIZi9YNEkKLS0tIElTdlRxL21TNXZYaXg4RFFtdDYy
            Qi9oeEFoUTN4MDYySEdXUkEzaHA0b1UK9gqH2rAvf+Jlft//R3QZHOsCNtv9TpNO
            QO/2gL1xi3RowcdUtCFpN3lPaU+LKxIgUNlxtDTDN4nLBJXMrRaA2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T02:22:12Z"
    mac: ENC[AES256_GCM,data:ZXhKrolyeWteoI0T7pN/hObgZmOy4c0nfLkbg3RVA1QohUbC5b04GfeUt0sUi8xK7AtaCXZXtt2unu97xFrIQbmb7bvmLy0S2u9hxL/0voOe9Iyi+Xe/eyyVcg2992Y2gEiR6p6CyBVKCvdScOurtbJipK1GBfS5pmZKvJhBQRo=,iv:PwoJ0G8qR2IIMgHWBsQFtCTLEkTQaISwtALqSQawXaE=,tag:4PRf6VAJOMMaAHhqaUcaqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
