{
  imports = [
    ./lsp

    ./autolist-nvim.nix
    ./cmp.nix
    ./comment.nix
    ./conform-nvim.nix
    ./fugitive.nix
    ./gitsigns.nix
    ./hex.nix
    ./indent-blankline.nix
    ./lazygit.nix
    ./lualine.nix
    ./luasnip.nix
    ./markdown-preview.nix
    ./nix.nix
    ./nvim-autopairs.nix
    ./nvim-emmet.nix
    ./nvim-jdtls.nix
    ./oil.nix
    ./otter.nix
    ./scrollview.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
    ./tsc-nvim.nix
    ./vim-be-good.nix
    ./web-devicons.nix
  ];
}
