freshrss-passwd: ENC[AES256_GCM,data:MzE2X3Vv4/XVe/WTRi709Umyu4ALY+Uo16UyCF4RHA==,iv:XAIRWflluzRYjSe0+pENMb/NHfoXbn6OtJvxMnNzmnQ=,tag:5sEJwPSz0sQhBPz6e2RDBw==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:GdSD7tNqbH0w6X19k9MDllsR5GfB839D7/u1DN0LTa5XUzAH5vX+/CEFlbM=,iv:fd7+r+H1IToYmIuFTVPtgKxIMoO0lV/wqUblL4oKtj0=,tag:2c9C778nyw9WtZXidarJeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19676vq2d77cp6xekzrjp04zk24ymdnp32t42sqznuxkk8xe3w9fsqsphrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdEszMGdmRzdPUGZMVUJL
            Y3VGWTFCRjEwZS8vOWlydzM1Ynp5N0pVbFcwCnBBeVpsNHpxdEJhK2tOV0pSZjA3
            K2RHQTFCSHJ3anVwdzEyZGdselVSc2cKLS0tIGF6RmZ3R1RjZHE1UzZQREM2Ny8x
            RldZV1FVOVc3RTQ3RTlQUFRDazZGQ0EKfrU/c1sbpDEjij1oG8u5/xvW5hjaSypB
            JWXv8W0KTphvPA3tjOieQ/X49tOgjLyYle/Fkj6Sg37nq0EAEm1PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T01:31:39Z"
    mac: ENC[AES256_GCM,data:ZAt3flfDVDUaydOUSIXtB/gUWsgg1C5s6+CHWqTFoAywBJ8rXawl8qMvFPP1VoKTb3Za4WubD0ZLMdDCogCvwIW+XfaqcH5RV8guIqani5JvxwFAsJuwvrUxX9C5vn/to2Z7gpO/gl7gLECtUZimIUYP+r0xUSiNLpYUNiDCw0A=,iv:ArPXaThG5rJfyjG3a+OgP+Ra2ANzLu/wMNi2Z6sfTtw=,tag:gSpQjnmz4nj3p1XPTXqEeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
