freshrss-passwd: ENC[AES256_GCM,data:MzE2X3Vv4/XVe/WTRi709Umyu4ALY+Uo16UyCF4RHA==,iv:XAIRWflluzRYjSe0+pENMb/NHfoXbn6OtJvxMnNzmnQ=,tag:5sEJwPSz0sQhBPz6e2RDBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19676vq2d77cp6xekzrjp04zk24ymdnp32t42sqznuxkk8xe3w9fsqsphrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdEszMGdmRzdPUGZMVUJL
            Y3VGWTFCRjEwZS8vOWlydzM1Ynp5N0pVbFcwCnBBeVpsNHpxdEJhK2tOV0pSZjA3
            K2RHQTFCSHJ3anVwdzEyZGdselVSc2cKLS0tIGF6RmZ3R1RjZHE1UzZQREM2Ny8x
            RldZV1FVOVc3RTQ3RTlQUFRDazZGQ0EKfrU/c1sbpDEjij1oG8u5/xvW5hjaSypB
            JWXv8W0KTphvPA3tjOieQ/X49tOgjLyYle/Fkj6Sg37nq0EAEm1PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T22:51:53Z"
    mac: ENC[AES256_GCM,data:h7vOOcJWaERPHsMcwk2umTQ3xlntOxmcfLwDQ2Ns5xgwOjaoKvFEXwtefX84TKxs7THG+AAt/2Gd9rBPNteocVClLbJW61orAat0Sxz5K36qcjdSJFhMQGpvJVWsfaoLi4fSPhQheu70VGV/ATdLHkZfBQUXNfKZefDa2taQL9o=,iv:0oS5jkA7ppME9VAoo83NjGNUNcfZXScRe0/EeahUCfw=,tag:b2japT7rvVKN/1gyfIH9BA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
